# FOSRestBundle Configuration
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
            -
                priorities: ['json', 'html']
    view:
        view_response_listener: true
