imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assetic.yml }
    # FriendOfSymfony Bundles
    - { resource: fos/fos_user.yml }
    - { resource: fos/fos_rest.yml }
    - { resource: fos/fos_message.yml }
    - { resource: fos/fos_oauth_server.yml }
    # Sonata Core Bundles
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_formatter.yml }
    - { resource: sonata/sonata_timeline.yml }
    - { resource: sonata/sonata_core.yml }
    - { resource: sonata/sonata_cache.yml }
    - { resource: sonata/sonata_seo.yml }
    # Sonata Feature Bundles
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_news.yml }
    - { resource: sonata/sonata_user.yml }
    - { resource: sonata/sonata_notification.yml }
    - { resource: sonata/sonata_page.yml }
    # HWI
    - { resource: hwi/hwi_oauth.yml }


framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session: ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    base_template_class: Sonata\CacheBundle\Twig\TwigTemplate14
    form:
        resources:
            - 'SonataFormatterBundle:Form:formatter.html.twig'
            - 'SonataMediaBundle:Form:media_widgets.html.twig'
            - 'SonataCoreBundle:Form:datepicker.html.twig'

    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'


# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"
        ## sonata user
        types:
            json: Sonata\Doctrine\Types\JsonType
        ## ignore migration session table
        schema_filter: ~^(?!session)~

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sensio_framework_extra:
    view:    { annotations: false }  # for FOSRestBundle
    router:  { annotations: true }
    request: { converters:  true }




#fp_open_id:
#    db_driver: orm
#    identity_class: Openpp\UserBundle\Entity\OpenIdIdentity
