ApiDocBundle:
    resource:     "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:       /doc

sonata_api_classification:
    type:         rest
    prefix:       /classification
    resource:     "@SonataClassificationBundle/Resources/config/routing/api.xml"

sonata_api_media:
    type:         rest
    prefix:       /media
    resource:     "@SonataMediaBundle/Resources/config/routing/api.xml"

sonata_api_notification:
    type:         rest
    prefix:       /notification
    resource:     "@SonataNotificationBundle/Resources/config/routing/api.xml"

sonata_api_user:
    type:         rest
    prefix:       /user
    resource:     "@SonataUserBundle/Resources/config/routing/api.xml"

openpp_api_push:
    type:         rest
    prefix:       /push
    resource:     "@OpenppPushNotificationBundle/Resources/config/routing/api.xml"

openpp_api_oauth_verify:
    type:         rest
    prefix:       /verify
    resource:     Application\FOS\OAuthServerBundle\Controller\Api\VerifyController
