sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

news:
    resource: '@SonataNewsBundle/Resources/config/routing/news.xml'
    prefix: /news

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

#fp_openid_security:
#    resource: "@FpOpenIdBundle/Resources/config/routing/security.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /message

# FOS User
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#OAuth
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

facebook_login:
    pattern: /login/check-facebook

openpp_toppage:
    resource: "@OpenppToppageBundle/Resources/config/routing.yml"
    prefix:   /

openpp_timeline:
    resource: "@OpenppTimelineBundle/Resources/config/routing.yml"
    prefix:   /

#application_sonata_user_profile:
#    resource: '@ApplicationSonataUserBundle/Resources/config/routing/profile.xml'
#    prefix: /profile

application_sonata_user_friend:
    resource: '@ApplicationSonataUserBundle/Resources/config/routing/friend.xml'
    prefix: /friend


    