# sonata project
sonata_admin:
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

    title:      openpp Admin
    templates:
        # default global templates
        # the layout template include javascript/stylesheet to the formatter bundle,
        # if you don't need it use the default one: SonataAdminBundle::standard_layout.html.twig
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default value if done set, actions templates, should extends a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
        dashboard: SonataAdminBundle:Core:dashboard.html.twig

    dashboard:
        groups:
            sonata_content:
                icon:            '<i class="fa fa-th"></i>'
                label:           Content
                items:
                    - sonata.media.admin.media
                    - sonata.media.admin.gallery
            sonata_classification:
                items: ~
                icon:            '<i class="fa fa-sitemap"></i>'
                label_catalogue: "SonataClassificationBundle"
            sonata.admin.group.site_builder:
                label:           Site Builder
                label_catalogue: "SonataPageBundle"
                icon:            '<i class="fa fa-puzzle-piece"></i>'
                items:
                    - sonata.page.admin.page
                    - sonata.page.admin.site
            sonata.admin.group.administration:
                label:           sonata_administration
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-cogs"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
            application_fos_oauth_server.admin.client:
                label:           OAuth
                icon:            '<i class="fa fa-cogs"></i>'
                items:
                    - application_fos_oauth_server.admin.client
            openpp.admin.group.push_notification:
                label:           Push Notification
                icon:            '<i class="fa fa-mobile"></i>'
                label_catalogue: "OpenppPushNotificationBundle"
                items:
                    - openpp.push_notification.admin.application
                    - openpp.push_notification.admin.device
                    - openpp.push_notification.admin.user
                    - openpp.push_notification.admin.tag
                    - openpp.push_notification.admin.condition

    assets:
        stylesheets:
            - assetic/sonata_admin_css.css
            - assetic/sonata_formatter_css.css
            - assetic/sonata_jqueryui_css.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.min.css
        javascripts:
            - assetic/sonata_admin_js.js
            - assetic/sonata_jqueryui_js.js
            - assetic/sonata_formatter_js.js
            - bundles/sonataformatter/vendor/ckeditor/ckeditor.js
