cmf_routing:
    chain:
        routers_by_id:
            # enable the DynamicRouter with high priority to allow overwriting configured routes with content
            #cmf_routing.dynamic_router: 200
            # enable the symfony default router with a lower priority
            sonata.page.router: 150
            router.default: 100

sonata_page:
    multisite: host
    use_streamed_response: true # set the value to false in debug mode or if the reverse proxy does not handle streamed response
    ignore_route_patterns:
        - ^(.*)admin(.*)   # ignore admin route, ie route containing 'admin'
        - ^_(.*)          # ignore symfony routes
        - ^/login(.*)
        - ^/oauth(.*)

    ignore_routes:
        - sonata_page_cache_esi
        - sonata_page_cache_ssi
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_apc

    ignore_uri_patterns:
        - ^/admin(.*)
        - ^/api/(.*)
#        - ^/login(.*)
        - ^/oauth(.*)

    assets:
        stylesheets:
            - assetic/sonata_front_css.css
        javascripts:
            - assetic/sonata_front_js.js

    page_defaults:
        homepage: { decorate: false, enabled: true }

    default_template: simple # template key from templates section, used as default for pages
    #templates:
    #    default:  { path: 'SonataPageBundle::layout.html.twig',          name: 'default' }
    #    2columns: { path: 'SonataPageBundle::2columns_layout.html.twig', name: '2 columns layout' }
    templates:
        plain:
            path: 'ApplicationSonataPageBundle::plain_layout.html.twig'
            name: 'plain'
            containers:
                 header:
                     name: Header
                 content_top:
                     name: Top content
                 content:
                     name: Main content
                 content_bottom:
                     name: Bottom content
                 footer:
                     name: Footer
            matrix:
                 layout: |
                     HHHHHHHH
                     TTTTTTTT
                     CCCCCCCC
                     BBBBBBBB
                     FFFFFFFF
                 mapping:
                     H: header
                     T: content_top
                     C: content
                     B: content_bottom
                     F: footer
    # manage the http errors
    catch_exceptions:
        not_found: [404]    # render 404 page with "not_found" key (name generated: _page_internal_error_{key})
        fatal:     [500]    # so you can use the same page for different http errors or specify specific page for each error
