spy_timeline:
    drivers:
        orm:
            object_manager: doctrine.orm.entity_manager
            classes:
                query_builder: ~ # Spy\TimelineBundle\Driver\ORM\QueryBuilder\QueryBuilder
                timeline:  Openpp\TimelineBundle\Entity\Timeline
                action:    Openpp\TimelineBundle\Entity\Action
                component: Openpp\TimelineBundle\Entity\Component
                action_component: Openpp\TimelineBundle\Entity\ActionComponent
    filters:
        data_hydrator:
            priority:             20
            service:              spy_timeline.filter.data_hydrator
            filter_unresolved:    false
            locators:
                - spy_timeline.filter.data_hydrator.locator.doctrine_orm
    render:
        path:     'AcmeTimelineBundle:Timeline'
        resources:
            - 'AcmeTimelineBundle:Timeline:components.html.twig'
    paginator: ~
