services:
    application_fos_oauth_server.admin.client:
        class: Application\FOS\OAuthServerBundle\Admin\ClientAdmin
        arguments: [~, Application\FOS\OAuthServerBundle\Entity\Client, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Client}

    application_fos_oauth_server.oauth_event_listener:
        class: Application\FOS\OAuthServerBundle\EventListener\OAuthEventListener
        arguments:
            - @service_container
        tags:
            - { name: kernel.event_listener, event: fos_oauth_server.pre_authorization_process, method: onPreAuthorizationProcess }
            - { name: kernel.event_listener, event: fos_oauth_server.post_authorization_process, method: onPostAuthorizationProcess }