parameters:
#    acme_timeline.example.class: Acme\TimelineBundle\Example

services:
    acme.timeline.twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    acme.timeline.spread:
        class: Acme\TimelineBundle\Spread\Spread
        tags:
            - { name: spy_timeline.spread }
