parameters:
#    acme_timeline.example.class: Openpp\TimelineBundle\Example

services:
    openpp.timeline.twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    openpp.timeline.spread:
        class: Openpp\TimelineBundle\Spread\Spread
        tags:
            - { name: spy_timeline.spread }
