parameters:
#    acme_user.example.class: Openpp\UserBundle\Example

services:
#    acme_user.example:
#        class: %acme_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

