<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use FOS\MessageBundle\Model\ParticipantInterface;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser implements ParticipantInterface
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param Array
     */
    public function setFBData($fbdata)
    {
        if (isset($fbdata['id'])) {
            $this->setFacebookUid($fbdata['id']);
            $this->setUsername($fbdata['id']);
            $this->addRole('ROLE_FACEBOOK');
        }
        if (isset($fbdata['first_name'])) {
            if (!$this->getFirstname()) {
                $this->setFirstname($fbdata['first_name']);
            }
        }
        if (isset($fbdata['last_name'])) {
            if (!$this->getLastname()) {
                $this->setLastname($fbdata['last_name']);
            }
        }
        if (isset($fbdata['email'])) {
            if (!$this->getEmail()) {
                $this->setEmail($fbdata['email']);
            }
        }
    }
}