parameters:
#    acme_help.example.class: Acme\HelpBundle\Example

services:
#    acme_help.example:
#        class: %acme_help.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
