parameters:
#    acme_help.example.class: Acme\HelpBundle\Example

services:
    acme.contact.form.type:
        class: Acme\HelpBundle\Form\ContactType
        tags:
            - { name: form.type, alias: acme_helpbundle_contact }
        arguments: [ @session ]
